
apiVersion: v1
kind: Service
metadata:
  name: formatterapp
  labels:
    app: formatterapp
spec:
  ports:
    - port: 9080
  selector:
    app: formatterapp
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: formatterapp
  name: formatterapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: formatterapp
    spec:
      containers:
      - image: mycluster.icp:8500/default/formatterapp:latest
        name: formatterapp
        ports:
        - containerPort: 9080
          protocol: TCP
